reviews/urls.py
# coding: utf-8

from django.conf.urls import url

from  . import views

urlpatterns = [
    url(r'^$', views.review_list, name='review_list'),
    url(r'^review/(?P<review_id>[0-9]+)/$', views.review_detail, name='review_detail'),
    url(r'^wine$', views.wine_list, name='wine_list'),
    url(r'^wine/(?P<wine_id>[0-9]+)/$', views.wine_detail, name='wine_detail'),
    url(r'^wine/(?P<wine_id>[0-9]+)/add_review/$', views.add_review, name='add_review'),
    # ex: /review/user - get reviews for the logged user
    url(r'^review/user/(?P<username>\w+)/$', views.user_review_list, name='user_review_list'),
    url(r'^review/user/$', views.user_review_list, name='user_review_list'),
]

winerama/urls.py
# coding: utf-8

"""winerama URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add an import:  from blog import urls as blog_urls
    2. Add a URL to urlpatterns:  url(r'^blog/', include(blog_urls))
"""
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^reviews/', include('reviews.urls', namespace="reviews")),
    url(r'^admin/', include(admin.site.urls)),
    url('^accounts/', include('registration.backends.simple.urls')),   # 教程使用simple -- 1.3修改成default -- 1.8 成功显示注册后的页面【安装django-registration-redux版本不同故障】
    url('^accounts/', include('django.contrib.auth.urls', namespace="auth")),   # 将 auth 应用中的 urls 模块包含进来
]

reviews/models.py
# coding: utf-8
# 添加中文注释要使用utf-8编码
from django.db import models
import numpy as np


class Wine(models.Model):
    name = models.CharField(max_length=200)
    
    def average_rating(self):
	# map(function, sequence) ：对sequence中的item依次执行function(item)，见执行结果组成一个List返回
	# lambda lambda其实就是一条语句，lambda(x):body。x是lambda函数的参数，参数可以有任意多个(包括可选参数);body是函数体，只能是一个表达式，并且直接返回该表达式的值
	# 对于用`` ForeignKey`` 来定义的关系来说，在关系的另一端也能反向的追溯回来【self.review_set.all()】
        all_ratings = map(lambda x: x.rating, self.review_set.all())
	# 求list平均值与average有区别
	# https://stackoverflow.com/questions/20054243/np-mean-vs-np-average-in-python-numpy
        return np.mean(all_ratings)
        
    def __unicode__(self):
        return self.name


class Review(models.Model):
    RATING_CHOICES = (
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5'),
    )
    wine = models.ForeignKey(Wine)
    pub_date = models.DateTimeField('date published')
    user_name = models.CharField(max_length=100)
    comment = models.CharField(max_length=200)
    rating = models.IntegerField(choices=RATING_CHOICES)
    

reviews/forms.py
# coding: utf-8
from django.forms import ModelForm, Textarea
from reviews.models import Review


class ReviewForm(ModelForm):
    # 表单的内部类 Meta
    class Meta:
        model = Review
        fields = ['rating', 'comment']     # 表单显示字段
        widgets = {
            'comment': Textarea(attrs={'cols': 40, 'rows': 15}),    # 重写字段的控件属性
        }

reviews/views.py
# coding: utf-8
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from .models import Review, Wine
from .forms import ReviewForm
import datetime

from django.contrib.auth.decorators import login_required

# Create your views here.
def review_list(request):
    # order_by QuerySet 根据模型Meta 类的ordering 选项排序
    # - 降序排序
    # 隐式的是升序排序。若要随机排序，请使用"?"
    # pub_date最大的9条
    latest_review_list = Review.objects.order_by('-pub_date')[:9]
    # 添加到模板上下文的一个字典
    context = {'latest_review_list':latest_review_list}
    return render(request, 'reviews/review_list.html', context)


def review_detail(request, review_id):
    # 调用django 的get方法，如果查询的对象不存在的话，会抛出一个DoesNotExist的异常
    # The following example gets the object with the primary key of review_id from Review
    review = get_object_or_404(Review, pk=review_id)
    return render(request, 'reviews/review_detail.html', {'review': review})


def wine_list(request):
    wine_list = Wine.objects.order_by('-name')
    context = {'wine_list':wine_list}
    return render(request, 'reviews/wine_list.html', context)


def wine_detail(request, wine_id):
    wine = get_object_or_404(Wine, pk=wine_id)
    form = ReviewForm()
    return render(request, 'reviews/wine_detail.html', {'wine': wine, 'form': form})


@login_required
def add_review(request, wine_id):
    wine = get_object_or_404(Wine, pk=wine_id)
    form = ReviewForm(request.POST)
    if form.is_valid():
        rating = form.cleaned_data['rating']
        comment = form.cleaned_data['comment']
        # user_name = form.cleaned_data['user_name']
        user_name = request.user.username
        review = Review()
        review.wine = wine
        review.user_name = user_name
        review.rating = rating
        review.comment = comment
        review.pub_date = datetime.datetime.now()
        review.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('reviews:wine_detail', args=(wine.id,)))    # 重定向

    return render(request, 'reviews/wine_detail.html', {'wine': wine, 'form': form})



def user_review_list(request, username=None):
    if not username:
        username = request.user.username
    latest_review_list = Review.objects.filter(user_name=username).order_by('-pub_date')
    context = {'latest_review_list':latest_review_list, 'username':username}
    return render(request, 'reviews/user_review_list.html', context)

reviews/templates/reviews/base.html
{% load bootstrap3 %}

{% bootstrap_css %}
{% bootstrap_javascript %}

{% block bootstrap3_content %}
<div class="container">     <!-- 水平居中，两边有margin，最小屏幕时，充满父元素 -->
    <nav class="navbar navbar-default">     <!-- .navbar用来表示该元素的语义：它是一个导航栏，Bootstrap将会以导航栏的方式来设置其子元素的样式。.navbar-default用来表示该元素的样式：使用default（默认）样式，即灰色的背景，黑色的文字。-->
        <div class="navbar-header">         <!-- 向 <div> 元素添加一个标题 class .navbar-header，内部包含了带有 class navbar-brand 的 <a> 元素。这会让文本看起来更大一号。 -->
            <a class="navbar-brand" href="{% url 'reviews:review_list' %}">Winerama</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">  <!-- 保证在窄屏时需要折叠的内容必须包裹在带一个div内，并且为这个div加入.collapse、.navbar-collapse两个类名。最后为这个div添加一个class类名或者id名。-->
            <ul class="nav navbar-nav">     <!-- 向导航栏添加链接 -->
                <li><a href="{% url 'reviews:wine_list' %}">Wine list</a></li>
                <li><a href="{% url 'reviews:review_list' %}">Home</a></li>
            </ul>
        </div>
    </nav>


    <h1>{% block title %}(no title){% endblock %}</h1>

    {% bootstrap_messages %}

    {% block content %}(no content){% endblock %}
</div>
{% endblock %}

reviews/templates/reviews/review_detail.html
{% extends 'base.html' %}

{% block title %}
<h2><a href="{% url 'reviews:wine_detail' review.wine.id %}">{{ review.wine.name }}</a></h2>
{% endblock %}

{% block content %}
    <h4>Rated {{ review.rating }} of 5 by <a href="{% url 'reviews:user_review_list' review.user_name %}" > {{ review.user_name }} </a></h4>
<p>{{ review.pub_date }}</p>
<P>{{ review.comment }}</P>
{% endblock %}

reviews/templates/reviews/review_list.html
{% extends 'base.html' %}

{% block title %}
<h2>Latest reviews</h2> <!-- 标题 -->
{% endblock %}


{% block content %}
{#{% if latest_review_list %} <!-- 函数返回该变量 -->#}
{#<div>#}
{#    {% for review in latest_review_list %}  <!-- django 模板 for 循环 -->#}
{#    <div>#}
{#        <h4><a href="{% url 'reviews:review_detail' review.id %}"  >   <!-- url 使用url.py定义的name -->#}
{#            {{ review.wine.name }}#}
{#        </a></h4>#}
{#        <h6>rated {{ review.rating }} of 5 by {{ review.user_name }}</h6>#}
{#        <p> {{ review.comment }}</p>#}
{#    </div>#}
{#    {% endfor %}#}
{#</div>#}
{#{% else %}      <!-- django if else endif 模板-->#}
{#<p>No reviews are available.</p>#}
{# {% endif %}#}

{% if latest_review_list %}
<div class="row">       <!-- Grid System Use rows to create horizontal groups of columns-->
    {% for review in latest_review_list %}
    <div class="col-xs-6 col-lg-4">     <!-- col-xs- 等宽的列；col-lg- 栅格类适用于与屏幕宽度大于或等于分界点大小的设备 ， 并且针对小屏幕设备覆盖栅格类 -->
        <h4><a href="{% url 'reviews:review_detail' review.id %}">
        {{ review.wine.name }}
        </a></h4>
        <h6>rated {{ review.rating }} of 5 by <a href="{% url 'reviews:user_review_list' review.user_name %}"> {{ review.user_name }} </a></h6>
        <p>{{ review.comment }}</p>
    </div>
    {% endfor %}
</div>
{% else %}
<p>No reviews are available.</p>
{% endif %}

{% endblock %}

reviews/templates/reviews/user_review_list.html
{% extends 'reviews/review_list.html' %}

{% block title %}
<h2>Review by {{ username }}</h2>
{% endblock %}

reviews/templates/reviews/wine_detail.html
{% extends 'base.html' %}
{% load bootstrap3 %}       <!--  load the bootstrap3 library and use the bootstrap_* tags: -->

{% block title %}
<h2>{{ wine.name }}</h2>
<h5>{{ wine.review_set.count }} reviews ({{ wine.average_rating | floatformat }} average rating)</h5>
{% endblock %}


{% block content %}
<h3>Recent reviews</h3>

{% if wine.review_set.all %}
<div>
    {% for review in wine.review_set.all %}
    <div>
        <em>{{ review.comment }}</em>   <!-- <em> 标签告诉浏览器把其中的文本表示为强调的内容。对于所有浏览器来说，这意味着要把这段文字用斜体来显示。-->
        <h6>Rated {{ review.rating }} of 5 by {{ review.user_name }}</h6>
        <h5><a href="{% url 'reviews:review_detail' review.id %}">
            Read more
        </a></h5>
    </div>
    {% endfor %}
</div>
{% else %}
<p>No reviews for this wine yet</p>
{% endif %}

<h3>Add your review</h3>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

{#<form action="{% url 'reviews:add_review' wine.id %}" method="post">#}
{#    {% csrf_token %}#}
{#    {{ form.as_p }}     <!-- as_p() 渲染表单为一系列的<p> 标签，每个<p> 标签包含一个字段；<p> 一个段落 -->#}
{#    <input type="submit" value="Add" />#}
{#</form>#}

<form action="{% url 'reviews:add_review' wine.id %}" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form layout='inline' %}
    {% buttons %}
    <button type="submit" class="btn btn-primary">
        {% bootstrap_icon "star" %} Add
    </button>
    {% endbuttons %}
</form>

{% endblock %}

reviews/templates/reviews/wine_list.html
{% extends 'base.html' %}

{% block title %}
<h2>Wine list</h2>
{% endblock %}


{% block content %}
{% if wine_list %}
<div>
    {% for wine in wine_list %}
    <div>
        <h4><a href="{% url 'reviews:wine_detail' wine.id %}" >
        {{ wine.name }}
        </a></h4>
        <h5>{{ wine.review_set.count }}</h5>    <!-- ForeignKey relationship 获取评论的数量 -->
        <h5>{{ wine.average_rating | floatformat }} average rating</h5>    <!-- 保留1位小数，可为负数，几种形式 -->
    </div>
    {% endfor %}
</div>
{% else %}
<p>No wines are available.</p>
{% endif %}
{% endblock %}

templates/base.html
{% load bootstrap3 %}

{% bootstrap_css %}
{% bootstrap_javascript %}

{% block bootstrap3_content %}
<div class="container">     <!-- 水平居中，两边有margin，最小屏幕时，充满父元素 -->
    <nav class="navbar navbar-default">     <!-- .navbar用来表示该元素的语义：它是一个导航栏，Bootstrap将会以导航栏的方式来设置其子元素的样式。.navbar-default用来表示该元素的样式：使用default（默认）样式，即灰色的背景，黑色的文字。-->
        <div class="navbar-header">         <!-- 向 <div> 元素添加一个标题 class .navbar-header，内部包含了带有 class navbar-brand 的 <a> 元素。这会让文本看起来更大一号。 -->
            <a class="navbar-brand" href="{% url 'reviews:review_list' %}">Winerama</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">  <!-- 保证在窄屏时需要折叠的内容必须包裹在带一个div内，并且为这个div加入.collapse、.navbar-collapse两个类名。最后为这个div添加一个class类名或者id名。-->
            <ul class="nav navbar-nav">     <!-- 向导航栏添加链接 -->
                <li><a href="{% url 'reviews:wine_list' %}">Wine list</a></li>
                <li><a href="{% url 'reviews:review_list' %}">Home</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
                <li><a href="{% url 'reviews:user_review_list' user.username %}">Hello {{ user.username }}</a></li>
                <li><a href="{% url 'auth:logout' %}">Logout</a></li>
                {% else %}
                <li><a href="{% url 'auth:login' %}">Login</a></li>
                <li><a href="/accounts/register">Register</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>


    <h1>{% block title %}(no title){% endblock %}</h1>

    {% bootstrap_messages %}

    {% block content %}(no content){% endblock %}
</div>
{% endblock %}